sonar.organization=soat13
sonar.projectKey=soat13_fase-1-oficina
sonar.projectName=Fase 1 - Oficina

sonar.sources=.
sonar.exclusions=**/vendor/**,**/mocks/**,**/*_test.go,**/tests/**,**/scripts/**,**/assets/**,.env*,**/*.md,**/cmd/**,**/views.go,**/repository.go,**/bootstrap/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
