apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fiap
data:
  MIGRATIONS_DIR: "scripts/db/migrations"
  PORT: "8080"
  DD_DOGSTATSD_PORT: "8125"
  DD_TRACE_ENABLED: "true"
  LOG_LEVEL: "info"
  APP_ENV: "development"
  AWS_REGION: "us-east-1"
  SQS_BASE_URL: ${SQS_BASE_URL}