// Code generated by MockGen. DO NOT EDIT.
// Source: internal/estimate/application/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/soat13/fase-1-oficina/internal/estimate/domain"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByRepairOrderID mocks base method.
func (m *MockRepository) GetByRepairOrderID(ctx context.Context, repairOrderID uuid.UUID) (*domain.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRepairOrderID", ctx, repairOrderID)
	ret0, _ := ret[0].(*domain.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRepairOrderID indicates an expected call of GetByRepairOrderID.
func (mr *MockRepositoryMockRecorder) GetByRepairOrderID(ctx, repairOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRepairOrderID", reflect.TypeOf((*MockRepository)(nil).GetByRepairOrderID), ctx, repairOrderID)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, estimate *domain.Estimate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, estimate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, estimate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, estimate)
}

// SaveIfAwaitingStock mocks base method.
func (m *MockRepository) SaveIfAwaitingStock(ctx context.Context, estimate *domain.Estimate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIfAwaitingStock", ctx, estimate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIfAwaitingApproval mocks base method.
func (m *MockRepository) SaveIfAwaitingApproval(ctx context.Context, estimate *domain.Estimate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIfAwaitingApproval", ctx, estimate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIfAwaitingStock indicates an expected call of SaveIfAwaitingStock.
func (mr *MockRepositoryMockRecorder) SaveIfAwaitingStock(ctx, estimate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIfAwaitingStock", reflect.TypeOf((*MockRepository)(nil).SaveIfAwaitingStock), ctx, estimate)
}
